// Automatically generated by astro-icon
// 37eea1a5310939bdbf30611b1426d7f4f0fcb494f3b79ababd8c30663fa241eb

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "FacebookIcn"
		| "InstagramIcn"
		| "logo"
		| "logo-white"
		| "service"
		| "XIcn";
}