source:
paths:
  uploads: public
  static: public
collections_config:
  posts:
    path: "src/content/proyectos/posts"
    output: true
    url: /proyectos/[slug]/
    description: ""
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
_enabled_editors:
  - content
timezone: Etc/UTC
