paths:
  uploads: public
  uploads_filename: src/content/proyectos/posts/
  static: public
  collections: /src/content
collections_config:
  posts:
    path: src/content/proyectos/posts
    output: true
    url: src/content/proyectos/posts
    description: ""
    icon: notes
    _editables:
    _inputs:
      date:
        type: date
        label: Date
        description: Post date
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
timezone: Etc/UTC
