paths:
  uploads: public
  uploads_filename:
  static: public
  collections: /src/content

site_data:
  path: src/data

collections_config:
  posts:
    path: src/content/proyectos/posts
    output: false
    url: src/content/proyectos/posts
    description: ""
    icon: notes
    _editables:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    _inputs:
      src:
        type: image
        cascade: true
        schemas:
_inputs:
  src:
    type: image
    cascade: true
  date:
    type: date
    label: Date
    cascade: true
timezone: Etc/UTC
