source:
paths:
  uploads: public
  static: public
collections_config:
  posts:
    path: "src/content/proyectos/posts"
    output: true
    url: "/proyectos/[...slug]/"
    description: ""

timezone: Etc/UTC
