paths:
  uploads: public
  uploads_filename: src/content/proyectos/posts/
  static: public
  collections: /src/content

source:
_inputs:
  src:
    type: image

collections_config:
  posts:
    path: src/content/proyectos/posts
    output: true
    url: src/content/proyectos/posts
    description: ""
    icon: notes
    _editables:
    _inputs:
      src:
        type: image
    date:
      type: date
      options:
        timezone:
        empty_type:
        label: Date
        cascade: true
        description: Post date
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
timezone: Etc/UTC
